frame_grabber:
  video_source: "data/videos/input/platetest.mp4"
  fps_limit: 30 # Example, might not be used initially

vehicle_detector:
  model_path: "data/models/yolo11n.pt"
  conf_threshold: 0.5
  class_mapping:
    1: "person"
    2: "bicycle"
    3: "car"
    4: "motorcycle"
    6: "bus"
    8: "truck"

vehicle_tracker:
  tracker_type: "bytetrack"
  half: false
  device: "cpu"
  reid_model_path: None
  evolve_param_dict: None
  per_class: None

loguru:
  level: "DEBUG"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{process.name: <15}</cyan> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
  file_path: "logs/traffic_monitor.log"
  file_rotation: "10 MB"
  file_retention: "7 days"
  file_compression: "zip"
  terminal_output_enabled: true
  log_file_overwrite: true

lp_detector:
  model_path: "data/models/plate_v8n.pt"
  conf_threshold: 0.6

ocr_reader:
  hub_model_name: "global-plates-mobile-vit-v2-model"
  device: "auto"
  conf_threshold: 0.5

vehicle_counter:
  counting_lines:
    - # First line
      - [0, 750]
      - [1920, 750]

visualizer:
  font: cv2.FONT_HERSHEY_SIMPLEX
  font_scale: 0.6
  font_thickness: 2
  ocr_duration: 3.0

  class_colors:
    person: (0, 0, 255)
    bicycle: (0, 255, 0)
    car: (255, 0, 0)
    motorcycle: (255, 255, 0)
    bus: (0, 255, 255)
    truck: (255, 0, 255)
    default: (255, 255, 255)
