frame_grabber:
  video_source: "data/videos/input/platetest.mp4"
  fps_limit: 30 # Example, might not be used initially

vehicle_detector:
  model_path: "data/models/yolo11n.pt"
  conf_threshold: 0.5
  class_mapping:
    1: "person"
    2: "bicycle"
    3: "car"
    4: "motorcycle"
    6: "bus"
    7: "train"
    8: "truck"
